apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: election-mysql-deployment
  labels:
    app: election-mysql
spec:
  selector:
    matchLabels:
      app: election-mysql
      tier: election-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: election-mysql
        tier: election-mysql
    spec:
      containers:
      - image: 672001523455.dkr.ecr.us-east-1.amazonaws.com/electioncalcdockerdev_mysql
        name: election-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: election-mysql
              key: db_password
        ports:
        - containerPort: 3306
          name: election-mysql
        volumeMounts:
        - name: config-election-mysqld
          mountPath: /etc/mysql/mysql.conf.d
        - name: efs-election-mysql
          mountPath: /static
      volumes:
      - name: config-election-mysqld
        configMap:
          name: election-mysql
          items:
          - key: mysqld.cnf
            path: mysqld.cnf
      - name: efs-election-mysql
        persistentVolumeClaim:
          claimName: efs-election-mysql
