apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-02-28T22:02:00Z
  generation: 1
  labels:
    app: election-nginx
  name: election-nginx-deployment
  namespace: default
  resourceVersion: "1759750"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/election-nginx-deployment
  uid: 00779c83-1cd3-11e8-bfda-06b7117307b2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: election-nginx
      tier: election-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: election-nginx
        tier: election-nginx
    spec:
      containers:
      - image: 672001523455.dkr.ecr.us-east-1.amazonaws.com/electioncalcdockerdev_web
        imagePullPolicy: Always
        name: election-nginx
        ports:
        - containerPort: 8000
          name: election-nginx
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /static
          name: efs-election-ngix
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: efs-election-ngix
        persistentVolumeClaim:
          claimName: efs-election-nginx
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-02-28T22:02:02Z
    lastUpdateTime: 2018-02-28T22:02:02Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-02-28T22:02:00Z
    lastUpdateTime: 2018-02-28T22:02:02Z
    message: ReplicaSet "election-nginx-deployment-675c4fd5d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
