apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: election-mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: election-mysql-secrets
              key: db_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: config-election-mysqld
          mountPath: /etc/mysql/mysql.conf.d
        - name: efs-election-mysql
          mountPath: /datavol
      volumes:
      - name: config-election-mysqld
        configMap:
          name: election-mysqld-config
          items:
          - key: mysqld.cnf
            path: mysqld.cnf
      - name: efs-election-mysql
        persistentVolumeClaim:
          claimName: efs-election-mysql
