apiVersion: v1
kind: PersistentVolume
metadata:
  name: EFS-shinyapps-stg
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-051feb4d.efs.us-east-1.amazonaws.com
    path: "/"
