apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shinyapps-stg-deployment
  namespace: default
  labels:
    app: shinyapps-stg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shinyapps-stg
    spec:
      containers:
      - name: shinyapps-stg
        imagePullPolicy: Always
        image: 672001523455.dkr.ecr.us-east-1.amazonaws.com/shinyapps-stg:latest
        ports:
        - containerPort: 3838
        resources:
          limits:
            cpu: 200m
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 4Gi
        readinessProbe:
          httpGet:
            path: /
            port: 3838
        volumeMounts:
           - name: efs-pvc
             mountPath: /mnt
           - name: config-volume
             mountPath: /etc/shiny-server
      volumes:
      - name: efs-pvc
        persistentVolumeClaim:
          claimName: efs-shinyapps-stg
      - name: config-volume
        configMap:
          name: shiny-server-config
          items:
          - key: shiny-server.conf
            path: shiny-server.conf
