apiVersion: v1
kind: Service
metadata:
  name: shinyapps-stg-svc
  namespace: default
  labels:
    app: shinyapps-stg
spec:
  type: LoadBalancer
  ports:
    - port: 3838
  selector:
    app: shinyapps-stg
