kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinyapps-stg-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
