apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: corenlp-deployment
spec:
  selector:
    matchLabels:
      app: corenlp
  replicas: 2
  template:
    metadata:
      labels:
        app: corenlp
    spec:
      containers:
      - name: corenlp-complete-custom
        image: graham3333/corenlp-complete-custom
        ports:
        - name: corenlp-port
          containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: corenlp-service
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
  selector:
     app: corenlp
  type: LoadBalancer