apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - /usr/src/app/uwsgi/init.sh
        env:
        - name: MYSQL_CONTAINER_NAME
          value: mysql
        - name: MYSQL_DATABASE
          value: tpc_election_calculator
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: root
        image: web
        name: web
        resources: {}
        volumeMounts:
        - mountPath: /static
          name: web-claim0
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
status: {}
