apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: piwik-mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: solr-mysql-secrets
              key: db_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /datavol
        - name: config-piwik-mysqld
          mountPath: /etc/mysql/mysql.conf.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: piwik-mysql
      - name: config-piwik-mysqld
        configMap:
          name: piwik-mysqld-config
          items:
          - key: mysqld.cnf
            path: mysqld.cnf
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: us-east-1e
